services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change-me
      - N8N_ENCRYPTION_KEY=replace-with-32byte-key
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: {}
