name: gitleaks
on: [push, pull_request]
permissions:
  contents: read
  security-events: write  # for SARIF upload

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh \
            | bash -s -- -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          gitleaks version

      - name: Run gitleaks (no git history, allowlist)
        run: |
          gitleaks detect \
            --no-git \
            --redact \
            --config=.gitleaks.toml \
            --report-format sarif \
            --report-path results.sarif

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
